all:
	g++ -framework OpenGL -framework GLUT -o cohen_sutherland cohen_sutherland.cpp

cohen_sutherland:
	g++ -framework OpenGL -framework GLUT -o cohen_sutherland cohen_sutherland.cpp

clean:
	rm -f cohen_sutherland