all:
	gcc -o house_reflect_rotate house_reflect_rotate.c -lglut -lGL -lGLU -lm
	gcc -o spin_cube spin_cube.c -lglut -lGL -lGLU -lm

house_reflect_rotate:
	gcc -o house_reflect_rotate house_reflect_rotate.c -lglut -lGL -lGLU -lm

spin_cube:
	gcc -o spin_cube spin_cube.c -lglut -lGL -lGLU -lm

clean:
	rm house_reflect_rotate spin_cube