all:
	g++ mousedraw.cpp -o mousedraw.o -lGL -lGLU -lglut
	g++ drawrect.cpp -o drawrect.o -lGL -lGLU -lglut

mousedraw:
	g++ mousedraw.cpp -o mousedraw.o -lGL -lGLU -lglut

drawrect:
	g++ drawrect.cpp -o drawrect.o -lGL -lGLU -lglut

clean:
	rm *.o